import type { Metadata } from "next"
import "./globals.css"
import '@ant-design/v5-patch-for-react-19'
import NavBar from "@/components/NavBar"
import { AntdRegistry } from '@ant-design/nextjs-registry'
import Notification from '@/components/Notification'
export const metadata: Metadata = {
  title: "MLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <NavBar></NavBar>
          {children}
          <Notification />
        </AntdRegistry>
      </body>
    </html>
  )
}
